"""Athena -- an AI that learns by predicting what it is about to see."""

from .agent import (
    AgentConfig,
    AthenaAgent,
    CallableFoundation,
    Candidate,
    Decision,
    FoundationModel,
    OutcomeReport,
    ScoredCandidate,
    StrategyKnowledge,
)
from .baselines import BaselineReport, OnlineRLS
from .core import Athena, Config, StepReport
from .foundation import (
    DemoFoundation,
    FoundationError,
    FoundationRefusal,
    OpenAIResponsesFoundation,
    OpenAIResponsesToolReasoner,
    OpenRouterChatFoundation,
    OpenRouterChatToolReasoner,
)
from .memory import Belief, BeliefStore, Episode, EpisodicMemory, HashingEncoder
from .precision import Precision, VolatilityTracker
from .skills import (
    ConsolidationReport,
    Example,
    Experiment,
    KnowledgeGap,
    LearningReport,
    NovelTaskLearner,
    Program,
    ProgramCatalog,
    Skill,
    SkillRegistry,
    VerificationReport,
)
from .tool_learning import (
    DemoToolReasoner,
    OpaqueKVWorld,
    ProcedureStep,
    SkillValidation,
    ToolDecision,
    ToolEnvironment,
    ToolExperience,
    ToolGoal,
    ToolLearningAgent,
    ToolLearningReport,
    ToolParameter,
    ToolPolicy,
    ToolReasoner,
    ToolResult,
    ToolRunReport,
    ToolSkill,
    ToolSkillRegistry,
    ToolSpec,
    ToolVerification,
    make_validation_cases,
)
from .world import (
    Regime,
    SwitchingWorld,
    linear_mse,
    persistence_mse,
    shifting_world,
    smooth_world,
    zero_mse,
)

__all__ = [
    "Athena",
    "Config",
    "StepReport",
    "AthenaAgent",
    "AgentConfig",
    "FoundationModel",
    "CallableFoundation",
    "Candidate",
    "ScoredCandidate",
    "Decision",
    "OutcomeReport",
    "StrategyKnowledge",
    "DemoFoundation",
    "OpenAIResponsesFoundation",
    "OpenAIResponsesToolReasoner",
    "OpenRouterChatFoundation",
    "OpenRouterChatToolReasoner",
    "FoundationError",
    "FoundationRefusal",
    "HashingEncoder",
    "Episode",
    "EpisodicMemory",
    "Belief",
    "BeliefStore",
    "Program",
    "ProgramCatalog",
    "Example",
    "Experiment",
    "KnowledgeGap",
    "VerificationReport",
    "Skill",
    "ConsolidationReport",
    "LearningReport",
    "SkillRegistry",
    "NovelTaskLearner",
    "ToolParameter",
    "ToolSpec",
    "ToolGoal",
    "ToolDecision",
    "ToolResult",
    "ToolExperience",
    "ToolVerification",
    "ToolRunReport",
    "ToolEnvironment",
    "ToolReasoner",
    "ToolPolicy",
    "ProcedureStep",
    "SkillValidation",
    "ToolSkill",
    "ToolLearningReport",
    "ToolSkillRegistry",
    "OpaqueKVWorld",
    "DemoToolReasoner",
    "ToolLearningAgent",
    "make_validation_cases",
    "BaselineReport",
    "OnlineRLS",
    "Precision",
    "VolatilityTracker",
    "Regime",
    "SwitchingWorld",
    "shifting_world",
    "smooth_world",
    "persistence_mse",
    "linear_mse",
    "zero_mse",
]
__version__ = "0.6.0"
